export const playerConfig = {
  startPosition: [0, 3, 12] as [number, number, number],
  colliderRadius: 0.5,
  colliderSegmentHeight: 1.2,
  standingEyeHeight: 0.72,
  crouchingEyeHeight: 0.2,
  crouchLerpSpeed: 12,
  mouseSensitivity: 0.005,
  baseFov: 75,
  fovLerpSpeed: 14,
  groundCheckDistance: 1.32,
  groundCheckTolerance: 0.08,
  walkSpeed: 15,
  crouchSpeedMultiplier: 0.55,
  groundAcceleration: 38,
  groundFriction: 15,
  airAcceleration: 13,
  airControl: 0.62,
  maxGroundSpeed: 18,
  maxAirSpeed: 24,
  maxBhopSpeed: 28,
  jumpForce: 7.1,
  jumpCooldownMs: 80,
  groundedStickVelocity: -0.5,
};
